/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bibliotecasistema;

import bibliotecasistema.Livro;
import javax.swing.BoxLayout;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
 *
 * @author Elise
 */


    /**
     * Creates new form Biblioteca_Help
     */
    public Biblioteca_Help() {
        initComponents();
        
    public class Biblioteca_Help extends javax.swing.JPanel {
        
           
    public class Bibliotecasistema extends JPanel {

        private final ArrayList<Livro> livros = new ArrayList<>();
        private final DefaultListModel<String> listModel = new DefaultListModel<>();

        private JButton jButtonAdicionar;
        private JLabel jLabel1, jLabel2, jLabel3;
        private JList<String> jListLivros;
        private JScrollPane jScrollPane1;
        private JTextField jTextFieldAno, jTextFieldAutor, jTextFieldTitulo;

        public Bibliotecasistema() {
            initComponents();
            jListLivros.setModel(listModel);
        }

        private void initComponents() {
            jLabel1 = new JLabel("Título:");
            jLabel2 = new JLabel("Autor:");
            jLabel3 = new JLabel("Ano de Publicação:");

            jTextFieldTitulo = new JTextField(20);
            jTextFieldAutor = new JTextField(20);
            jTextFieldAno = new JTextField(10);

            jButtonAdicionar = new JButton("Adicionar Livro");
            jButtonAdicionar.addActionListener(evt -> jButtonAdicionarActionPerformed());

            jListLivros = new JList<>();
            jScrollPane1 = new JScrollPane(jListLivros);

            // Layout do painel
            setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));

            add(jLabel1);
            add(jTextFieldTitulo);
            add(jLabel2);
            add(jTextFieldAutor);
            add(jLabel3);
            add(jTextFieldAno);
            add(jButtonAdicionar);
            add(jScrollPane1);
        }

        private void jButtonAdicionarActionPerformed() {
            String titulo = jTextFieldTitulo.getText();
            String autor = jTextFieldAutor.getText();
            int ano = Integer.parseInt(jTextFieldAno.getText());

            Livro livro = new Livro(titulo, autor, ano);
            livros.add(livro);
            listModel.addElement(livro.toString());

            jTextFieldTitulo.setText("");
            jTextFieldAutor.setText("");
            jTextFieldAno.setText("");
        }

        // Método para retornar o painel e adicioná-lo a um JFrame
        public JPanel getPanel() {
            return this;
        }

        // Teste do JPanel dentro de um JFrame
        public static void main(String[] args) {
            JFrame frame = new JFrame("Sistema Biblioteca");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setSize(400, 300);
            frame.add(new Biblioteca_Help());
            frame.setVisible(true);
        }
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

